main.o: main.c input.h bitmap_types.h ms_types.h output.h my_vla.h \
 errors.h
input.o: input.c input.h bitmap_types.h ms_types.h errors.h my_vla.h
output.o: output.c output.h bitmap_types.h ms_types.h errors.h
my_vla.o: my_vla.c my_vla.h bitmap_types.h ms_types.h errors.h
