main.o: main.c input.h bitmap_types.h ms_types.h output.h my_vla.h \
 errors.h analyze.h
input.o: input.c input.h bitmap_types.h ms_types.h errors.h my_vla.h
output.o: output.c errors.h my_vla.h bitmap_types.h ms_types.h output.h
my_vla.o: my_vla.c my_vla.h bitmap_types.h ms_types.h errors.h
analyze.o: analyze.c my_vla.h bitmap_types.h ms_types.h errors.h list.h \
 analyze.h
list.o: list.c list.h analyze.h bitmap_types.h ms_types.h errors.h
